matrix:
  include:
    - language: python
      python: 3.6
      env:
        - FLASK_APP=autoapp.py
        - FLASK_CONFIG=dev.cfg
        - FLASK_DEBUG=1
      addons:
        chrome: stable
        sauce_connect:
          username: "glsorre"
          access_key: "4c0304aa-bba2-4bb2-959b-e4b05459bda2"
      before_install:
        - source $HOME/.nvm/nvm.sh
        - nvm install stable
        - nvm use stable
        - python3.6 --version
        - cd neaps-api/
        - echo "@@@ Installing API requirements @@@"
        - pip install -r requirements.txt
        - flask run 2&>1 &
        - cd ../neaps-spa/
      install:
        - echo "@@@ Installing SPA requirements @@@"
        - npm install
      script:
        - echo "@@@ Launching SPA tests @@@"
        - npm run test
    
    - language: python
      python: 3.6
      env:
        - FLASK_APP=autoapp.py
        - FLASK_CONFIG=dev.cfg
        - FLASK_DEBUG=1
      before_install:
        - cd neaps-api/
      install:
        - echo "@@@ Installing API requirements @@@"
        - pip install -r requirements.txt
        - pip install nose
      script:
        - echo "@@@ Running API tests @@@"
        - nosetests
      # after_success:
      #   - echo "@@@ Run dev server @@@"
      #   - flask run
