matrix:
  include:
    - language: python
      python: 3.6
      env:
        - FLASK_APP=autoapp.py
        - FLASK_CONFIG=dev.cfg
        - FLASK_DEBUG=1
        - DISPLAY=:99.0
      addons:
        # firefox: latest
        apt:
          sources:
          - google-chrome
          packages:
          - google-chrome-stable fluxbox
      before_install:
        - "sh -e /etc/init.d/xvfb start"
        - sleep 3
        - fluxbox >/dev/null 2>&1 &
        - source $HOME/.nvm/nvm.sh
        - nvm install stable
        - nvm use stable
        - python3.6 --version
        - cd neaps-api/
        - echo "@@@ Installing API requirements @@@"
        - pip install -r requirements.txt
        - flask run >/dev/null 2>&1 &
        - cd ../neaps-spa/
      install:
        - echo "@@@ Installing SPA requirements @@@"
        - npm install
      script:
        - echo "@@@ Launching SPA tests @@@"
        - npm run unit
        - npm run end2end
    
    - language: python
      python: 3.6
      env:
        - FLASK_APP=autoapp.py
        - FLASK_CONFIG=dev.cfg
        - FLASK_DEBUG=1
      before_install:
        - cd neaps-api/
      install:
        - echo "@@@ Installing API requirements @@@"
        - pip install -r requirements.txt
        - pip install nose
      script:
        - echo "@@@ Running API tests @@@"
        - nosetests
      # after_success:
      #   - echo "@@@ Run dev server @@@"
      #   - flask run
