matrix:
  include:
    - language: node
      python: 3.6
      addons:
        chrome: stable
      before_install:
        - python --version
        - cd neaps-spa/
      install:
        - echo "@@@ Installing SPA requirements @@@"
        - npm install
      script:
        - echo "@@@ Launching SPA tests @@@"
        - npm run unit
    
    - language: python
      python: 3.6
      env:
        - FLASK_APP=autoapp.py
        - FLASK_CONFIG=dev.cfg
        - FLASK_DEBUG=1
      before_install:
        - cd neaps-api/
      install:
        - echo "@@@ Installing API requirements @@@"
        - pip install -r requirements.txt
      script:
        - echo "@@@ Running API tests @@@"
        - python -m unittest **/*_test.py
      after_success:
        - echo "@@@ Run dev server @@@"
        - flask run
