"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['neaps_cef.py']
#DATA_FILES = []
OPTIONS = {
    'packages': ['cefpython3', 'numpy', 'neaps_lib'],
    'optimize': 2,
    'resources': ['web']
}

setup(
    app=APP,
    #data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app', 'cefpython3']
)
